#!/bin/bash
# 02_run_diffdock_batch.sh
# ========================
# Launches DiffDock batch inference on the GPU server using nohup so the job
# continues running after the SSH session is closed.
#
# Prerequisites:
#   - conda environment "diffdock" installed (github.com/gcorso/DiffDock)
#   - tasks.csv already generated by 01_generate_csv.py
#   - Pre-trained model weights present under DiffDock/workdir/
#
# Usage:
#   conda activate diffdock
#   bash 02_run_diffdock_batch.sh
#
# Monitor progress:
#   tail -f /mnt/Coco/diffdock_run.log
#
# Check how many complexes finished:
#   ls /mnt/Coco/diffdock_results | wc -l

# ─── CONFIGURATION ────────────────────────────────────────────────────────────
DIFFDOCK_DIR="/mnt/Coco/DiffDock"
TASKS_CSV="/mnt/Coco/tasks.csv"
OUTPUT_DIR="/mnt/Coco/diffdock_results"
LOG_FILE="/mnt/Coco/diffdock_run.log"

# DiffDock inference parameters
INFERENCE_STEPS=20       # Number of reverse diffusion steps
ACTUAL_STEPS=18          # Actual steps used (slightly fewer than total)
SAMPLES_PER_COMPLEX=1    # Pose samples per complex (1 = only best pose, faster)
BATCH_SIZE=10            # Complexes processed per GPU batch
# ──────────────────────────────────────────────────────────────────────────────

cd "$DIFFDOCK_DIR" || { echo "ERROR: Cannot cd to $DIFFDOCK_DIR"; exit 1; }

echo "Starting DiffDock batch inference..."
echo "Input CSV : $TASKS_CSV"
echo "Output dir: $OUTPUT_DIR"
echo "Log file  : $LOG_FILE"
echo ""

nohup python -m inference \
    --protein_ligand_csv "$TASKS_CSV" \
    --out_dir            "$OUTPUT_DIR" \
    --inference_steps    "$INFERENCE_STEPS" \
    --actual_steps       "$ACTUAL_STEPS" \
    --samples_per_complex "$SAMPLES_PER_COMPLEX" \
    --batch_size         "$BATCH_SIZE" \
    --no_final_step_noise \
    --model_dir              "$DIFFDOCK_DIR/workdir/score_model" \
    --confidence_model_dir   "$DIFFDOCK_DIR/workdir/confidence_model" \
    >> "$LOG_FILE" 2>&1 &

PID=$!
echo "DiffDock running in background — PID: $PID"
echo "Run:  tail -f $LOG_FILE   to monitor progress"
echo "Run:  kill $PID           to stop the job"
